-- =====================================================================
-- Seed Data — Dayflow HRMS hr-data module
-- Safe to run repeatedly in a dev/test DB (uses fixed UUIDs + ON CONFLICT)
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- USERS  (password_hash values below are placeholder bcrypt-shaped
-- strings — replace with real hashes generated by the app layer)
-- ---------------------------------------------------------------------
INSERT INTO users (id, employee_code, email, password_hash, role, is_email_verified, is_active)
VALUES
  ('11111111-1111-1111-1111-111111111101', 'ADM-001', 'admin.raina@dayflow.com',
   '$2b$12$abcdefghijklmnopqrstuvKzT8YQ9Z3nQe1bJmO7yV4hR2sD6wXaG', 'ADMIN', TRUE, TRUE),
  ('11111111-1111-1111-1111-111111111102', 'HR-001',  'hr.mehta@dayflow.com',
   '$2b$12$abcdefghijklmnopqrstuvKzT8YQ9Z3nQe1bJmO7yV4hR2sD6wXbH', 'HR', TRUE, TRUE),
  ('11111111-1111-1111-1111-111111111103', 'EMP-101', 'ananya.sharma@dayflow.com',
   '$2b$12$abcdefghijklmnopqrstuvKzT8YQ9Z3nQe1bJmO7yV4hR2sD6wXcI', 'EMPLOYEE', TRUE, TRUE),
  ('11111111-1111-1111-1111-111111111104', 'EMP-102', 'rahul.verma@dayflow.com',
   '$2b$12$abcdefghijklmnopqrstuvKzT8YQ9Z3nQe1bJmO7yV4hR2sD6wXdJ', 'EMPLOYEE', TRUE, TRUE),
  ('11111111-1111-1111-1111-111111111105', 'EMP-103', 'priya.nair@dayflow.com',
   '$2b$12$abcdefghijklmnopqrstuvKzT8YQ9Z3nQe1bJmO7yV4hR2sD6wXeK', 'EMPLOYEE', FALSE, TRUE)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------
-- EMPLOYEE PROFILES
-- ---------------------------------------------------------------------
INSERT INTO employee_profiles (user_id, first_name, last_name, phone, address, date_of_birth, gender, emergency_contact_name, emergency_contact_phone)
VALUES
  ('11111111-1111-1111-1111-111111111101', 'Raina', 'Kapoor', '+91-9800011101', 'Bengaluru, India', '1985-02-11', 'Female', 'Amit Kapoor', '+91-9800011199'),
  ('11111111-1111-1111-1111-111111111102', 'Sunil', 'Mehta',  '+91-9800011102', 'Bengaluru, India', '1988-07-23', 'Male',   'Neha Mehta',   '+91-9800011198'),
  ('11111111-1111-1111-1111-111111111103', 'Ananya', 'Sharma','+91-9800011103', 'Pune, India',       '1996-11-02', 'Female', 'Rakesh Sharma','+91-9800011197'),
  ('11111111-1111-1111-1111-111111111104', 'Rahul', 'Verma',  '+91-9800011104', 'Hyderabad, India',  '1994-05-19', 'Male',   'Sonia Verma',  '+91-9800011196'),
  ('11111111-1111-1111-1111-111111111105', 'Priya', 'Nair',   '+91-9800011105', 'Kochi, India',      '1998-01-30', 'Female', 'Anil Nair',    '+91-9800011195')
ON CONFLICT (user_id) DO NOTHING;

-- ---------------------------------------------------------------------
-- JOB DETAILS
-- ---------------------------------------------------------------------
INSERT INTO job_details (user_id, department, designation, employment_type, date_of_joining, reporting_manager_id, employment_status)
VALUES
  ('11111111-1111-1111-1111-111111111101', 'Administration', 'System Administrator', 'FULL_TIME', '2020-01-15', NULL, 'ACTIVE'),
  ('11111111-1111-1111-1111-111111111102', 'Human Resources', 'HR Officer', 'FULL_TIME', '2021-03-01', '11111111-1111-1111-1111-111111111101', 'ACTIVE'),
  ('11111111-1111-1111-1111-111111111103', 'Engineering', 'Software Engineer', 'FULL_TIME', '2022-06-10', '11111111-1111-1111-1111-111111111102', 'ACTIVE'),
  ('11111111-1111-1111-1111-111111111104', 'Engineering', 'Senior Software Engineer', 'FULL_TIME', '2019-09-05', '11111111-1111-1111-1111-111111111102', 'ACTIVE'),
  ('11111111-1111-1111-1111-111111111105', 'Design', 'UI/UX Designer', 'CONTRACT', '2023-02-20', '11111111-1111-1111-1111-111111111102', 'ACTIVE')
ON CONFLICT (user_id) DO NOTHING;

-- ---------------------------------------------------------------------
-- SALARY STRUCTURES (one active row per user)
-- ---------------------------------------------------------------------
INSERT INTO salary_structures (id, user_id, basic_pay, hra, conveyance_allowance, medical_allowance, special_allowance, tax_deduction, provident_fund, other_deductions, effective_from, is_active, created_by)
VALUES
  ('22222222-2222-2222-2222-222222222201', '11111111-1111-1111-1111-111111111103',
   45000, 18000, 2000, 1500, 5000, 4200, 3600, 0, '2022-06-10', TRUE, '11111111-1111-1111-1111-111111111101'),
  ('22222222-2222-2222-2222-222222222202', '11111111-1111-1111-1111-111111111104',
   72000, 28000, 2000, 1500, 8000, 8100, 5760, 0, '2019-09-05', TRUE, '11111111-1111-1111-1111-111111111101'),
  ('22222222-2222-2222-2222-222222222203', '11111111-1111-1111-1111-111111111105',
   38000, 15000, 2000, 1500, 3000, 2900, 3040, 0, '2023-02-20', TRUE, '11111111-1111-1111-1111-111111111101')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------
-- LEAVE BALANCES (2026 quotas)
-- ---------------------------------------------------------------------
INSERT INTO leave_balances (user_id, leave_type, year, total_allocated, used)
VALUES
  ('11111111-1111-1111-1111-111111111103', 'PAID', 2026, 18, 0),
  ('11111111-1111-1111-1111-111111111103', 'SICK', 2026, 10, 0),
  ('11111111-1111-1111-1111-111111111104', 'PAID', 2026, 18, 0),
  ('11111111-1111-1111-1111-111111111104', 'SICK', 2026, 10, 0),
  ('11111111-1111-1111-1111-111111111105', 'PAID', 2026, 12, 0),
  ('11111111-1111-1111-1111-111111111105', 'SICK', 2026, 8, 0)
ON CONFLICT (user_id, leave_type, year) DO NOTHING;

-- ---------------------------------------------------------------------
-- ATTENDANCE — a sample work week for Ananya (EMP-101)
-- ---------------------------------------------------------------------
INSERT INTO attendance (user_id, attendance_date, check_in_time, check_out_time)
VALUES
  ('11111111-1111-1111-1111-111111111103', '2026-08-17', '2026-08-17 09:02:00+05:30', '2026-08-17 18:05:00+05:30'),
  ('11111111-1111-1111-1111-111111111103', '2026-08-18', '2026-08-18 09:10:00+05:30', '2026-08-18 18:00:00+05:30'),
  ('11111111-1111-1111-1111-111111111103', '2026-08-19', '2026-08-19 09:00:00+05:30', '2026-08-19 13:15:00+05:30'), -- half day
  ('11111111-1111-1111-1111-111111111103', '2026-08-20', '2026-08-20 08:55:00+05:30', '2026-08-20 18:10:00+05:30')
ON CONFLICT (user_id, attendance_date) DO NOTHING;

-- Explicit absence entry for Rahul (EMP-102)
INSERT INTO attendance (user_id, attendance_date, status)
VALUES ('11111111-1111-1111-1111-111111111104', '2026-08-18', 'ABSENT')
ON CONFLICT (user_id, attendance_date) DO NOTHING;

-- ---------------------------------------------------------------------
-- LEAVE REQUESTS
-- ---------------------------------------------------------------------
INSERT INTO leave_requests (id, user_id, leave_type, start_date, end_date, remarks, status)
VALUES
  ('33333333-3333-3333-3333-333333333301', '11111111-1111-1111-1111-111111111104',
   'SICK', '2026-08-25', '2026-08-26', 'Fever, need rest', 'PENDING'),
  ('33333333-3333-3333-3333-333333333302', '11111111-1111-1111-1111-111111111105',
   'PAID', '2026-09-01', '2026-09-03', 'Family function', 'PENDING')
ON CONFLICT (id) DO NOTHING;

-- Demonstrate the approval flow (fires trg_leave_status_change + notification trigger)
UPDATE leave_requests
   SET status = 'APPROVED'
 WHERE id = '33333333-3333-3333-3333-333333333302'
   AND status = 'PENDING';

INSERT INTO leave_approval_logs (leave_request_id, approver_id, decision, comments)
VALUES ('33333333-3333-3333-3333-333333333302', '11111111-1111-1111-1111-111111111102',
        'APPROVED', 'Approved — coverage arranged with team.')
ON CONFLICT DO NOTHING;

COMMIT;

-- ---------------------------------------------------------------------
-- Sanity checks (run manually after seeding)
-- ---------------------------------------------------------------------
-- SELECT * FROM v_employee_directory;
-- SELECT * FROM v_weekly_attendance WHERE user_id = '11111111-1111-1111-1111-111111111103';
-- SELECT * FROM leave_balances WHERE user_id = '11111111-1111-1111-1111-111111111105';
-- SELECT * FROM notifications WHERE user_id = '11111111-1111-1111-1111-111111111105';
