/**
 * payroll.js — Loads real payroll data from backend API
 */

requireAuth();

const logoutBtn = document.getElementById('logoutBtn');
if (logoutBtn) logoutBtn.addEventListener('click', logout);

// ─── DOM refs ─────────────────────────────────────────────────────────────────

const netPayHeading    = document.getElementById('netPayHeading');
const netPayHero       = document.getElementById('netPayHero');
const grossEarnings    = document.getElementById('grossEarnings');
const deductionsTotal  = document.getElementById('deductionsTotal');
const netPaySummary    = document.getElementById('netPaySummary');
const basicRow         = document.getElementById('basicRow');
const hraRow           = document.getElementById('hraRow');
const allowancesRow    = document.getElementById('allowancesRow');
const deductionsRow    = document.getElementById('deductionsRow');
const netTotalRow      = document.getElementById('netTotalRow');
const netRatioPct      = document.getElementById('netRatioPct');
const netRatioInsight  = document.getElementById('netRatioInsight');
const effectiveFrom    = document.getElementById('effectiveFrom');
const payrollStatus    = document.getElementById('payrollStatus');
const downloadBtn      = document.getElementById('downloadPayslip');
const loadingMsg       = document.getElementById('payrollLoading');
const errorMsg         = document.getElementById('payrollError');

// ─── Helpers ──────────────────────────────────────────────────────────────────

function fmt(amount, currency = 'INR') {
  if (amount === undefined || amount === null) return '—';
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency,
    maximumFractionDigits: 0,
  }).format(amount);
}

function setText(el, val) {
  if (el) el.textContent = val;
}

// ─── Render payroll ───────────────────────────────────────────────────────────

function renderPayroll(p) {
  const currency    = p.currency || 'INR';
  const gross       = (p.basic || 0) + (p.hra || 0) + (p.allowances || 0);
  const deductions  = p.deductions || 0;
  const net         = p.netSalary || (gross - deductions);
  const ratio       = gross > 0 ? Math.round((net / gross) * 100) : 0;
  const effDate     = p.effectiveFrom
    ? new Date(p.effectiveFrom).toLocaleDateString('en-IN', { year: 'numeric', month: 'long' })
    : '—';

  setText(netPayHeading,  effDate + ' • NET PAY');
  setText(netPayHero,     fmt(net, currency));
  setText(grossEarnings,  fmt(gross, currency));
  setText(deductionsTotal, fmt(deductions, currency));
  setText(netPaySummary,  fmt(net, currency));
  setText(basicRow,       fmt(p.basic, currency));
  setText(hraRow,         fmt(p.hra, currency));
  setText(allowancesRow,  fmt(p.allowances, currency));
  setText(deductionsRow,  '− ' + fmt(deductions, currency));
  setText(netTotalRow,    fmt(net, currency));
  setText(netRatioPct,    ratio + '%');
  setText(netRatioInsight, ratio + '% of your gross earnings were credited after deductions.');
  setText(effectiveFrom,  effDate);

  if (payrollStatus) payrollStatus.textContent = 'PAID';

  if (loadingMsg) loadingMsg.style.display = 'none';
}

// ─── Download payslip (plain text printout) ───────────────────────────────────

let _payrollData = null;

if (downloadBtn) {
  downloadBtn.addEventListener('click', () => {
    if (!_payrollData) return;
    const p = _payrollData;
    const currency = p.currency || 'INR';
    const gross    = (p.basic || 0) + (p.hra || 0) + (p.allowances || 0);
    const net      = p.netSalary || 0;
    const effDate  = p.effectiveFrom
      ? new Date(p.effectiveFrom).toLocaleDateString('en-IN', { year: 'numeric', month: 'long' })
      : '';

    const content = [
      '========================================',
      '         DAYFLOW HRMS — PAYSLIP         ',
      '========================================',
      `Employee ID   : ${p.employeeId}`,
      `Period        : ${effDate}`,
      '----------------------------------------',
      `Basic Salary  : ${fmt(p.basic, currency)}`,
      `HRA           : ${fmt(p.hra, currency)}`,
      `Allowances    : ${fmt(p.allowances, currency)}`,
      '----------------------------------------',
      `Gross Earnings: ${fmt(gross, currency)}`,
      `Deductions    : - ${fmt(p.deductions, currency)}`,
      '========================================',
      `NET SALARY    : ${fmt(net, currency)}`,
      '========================================',
      '',
      'Generated by Dayflow HRMS',
      new Date().toLocaleString(),
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `payslip-${p.employeeId}-${effDate.replace(/\s/g, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  });
}

// ─── Load data ────────────────────────────────────────────────────────────────

async function loadPayroll() {
  if (loadingMsg) loadingMsg.style.display = 'block';
  if (errorMsg)   errorMsg.style.display   = 'none';

  try {
    const res = await api.getMyPayroll();
    _payrollData = res.data;
    renderPayroll(_payrollData);
  } catch (err) {
    if (loadingMsg) loadingMsg.style.display = 'none';
    if (err.status === 404) {
      // No payroll structure configured yet
      if (errorMsg) {
        errorMsg.textContent = 'No payroll structure has been set up for your account yet. Contact HR.';
        errorMsg.style.display = 'block';
      }
    } else {
      if (errorMsg) {
        errorMsg.textContent = 'Failed to load payroll data. Please try again later.';
        errorMsg.style.display = 'block';
      }
    }
  }
}

loadPayroll();
